### DISCUSSION TITLE
Quine

### DISCUSSION THREAD

**Discussion by franky47** [franky47/actions-laboratory#11] [Blog Posts]
This is the GitHub action that will write a Markdown file from this discussion.

```yaml
name: Discussion to file

on:
  discussion:
    types:
      - created
      - edited
      - category_changed

jobs:
  discussionToFile:
    runs-on: ubuntu-latest
    if: ${{ github.event.discussion.category.slug == 'blog-posts' }}
    steps:
      - uses: actions/checkout@v3
      - id: slug
        run: echo "slug=$(echo '${{ github.event.discussion.title }}' | sed -e 's/[^[:alnum:]]/-/g' -e 's/^-*//' -e 's/-*$//' -e 's/--/-/g' | tr A-Z a-z)" >> $GITHUB_OUTPUT
      - name: Write File
        uses: DamianReeves/write-file-action@v1.2
        with:
          path: ./blog/${{ github.event.discussion.number }}.md
          contents: |
            ---
            title: ${{ github.event.discussion.title}}
            slug: ${{ steps.slug.outputs.slug }}
            updatedAt: ${{ github.event.discussion.updated_at }}
            publishedAt: ${{ github.event.discussion.created_at }}
            ---

            ${{ github.event.discussion.body }}

            [Comment this post on GitHub](${{ github.event.discussion.html_url }})
          write-mode: overwrite


      # - run: cat event.json
      # - run: cat event.json | jq -r '.body' > ./blog/${{ github.event.discussion.number }}.md
      - run: cat ./blog/${{ github.event.discussion.number }}.md
      # - run: rm -f event.json
      - name: Commit & Push
        uses: Andro999b/push@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: 'Overwritten by Github Actions - ${date}'
```
